"""LINK action grammar (docs/ml/01 §5).

A construction is generated by a token sequence
    ('ADD', block_type, init_state)   # add an instance in a given initial state
    ('MERGE', port_p, port_q)         # union the components of two global ports
    ('EXPOSE', port_p, target_x)      # attach target-port x to port_p's component
    ('STOP',)
Ports are global indices in ADD order. This M0 version reconstructs a construction
faithfully (round-trips to an isomorphic one); the fully-canonical action ordering
used to make search a tree (docs/ml/01 §5) is layered on in M1.
"""
from collections import defaultdict
from typing import List, Tuple

from .system import BlockSet, Construction

Action = Tuple


def apply(blockset: BlockSet, actions: List[Action]) -> Construction:
    inst: List[int] = []
    init: List[int] = []
    merges: List[Tuple[int, int]] = []
    exposes: List[Tuple[int, int]] = []
    for act in actions:
        tag = act[0]
        if tag == "ADD":
            inst.append(act[1])
            init.append(act[2] if len(act) > 2 else 0)
        elif tag == "MERGE":
            merges.append((act[1], act[2]))
        elif tag == "EXPOSE":
            exposes.append((act[1], act[2]))
        elif tag == "STOP":
            break
        else:
            raise ValueError(f"unknown action {act!r}")

    nports = sum(blockset.num_locations(t) for t in inst)
    parent = list(range(nports))

    def find(x):
        while parent[x] != x:
            parent[x] = parent[parent[x]]
            x = parent[x]
        return x

    for p, q in merges:
        parent[find(p)] = find(q)
    comp = [find(p) for p in range(nports)]

    k = 1 + max((x for _, x in exposes), default=-1)
    iface: List[int] = [None] * k
    for p, x in exposes:
        iface[x] = comp[p]
    if any(v is None for v in iface):
        raise ValueError("interface not fully assigned by EXPOSE actions")
    return Construction(blockset, inst, comp, iface, init)


def to_actions(c: Construction) -> List[Action]:
    acts: List[Action] = [("ADD", t, s0) for t, s0 in zip(c.instances, c.init)]
    comp_ports = defaultdict(list)
    for p in range(c.num_ports):
        comp_ports[c.wire[p]].append(p)
    for ports in comp_ports.values():
        base = ports[0]
        for other in ports[1:]:
            acts.append(("MERGE", min(base, other), max(base, other)))
    for x, comp in enumerate(c.iface):
        acts.append(("EXPOSE", comp_ports[comp][0], x))
    acts.append(("STOP",))
    return acts
