import argparse
import sys
import yaml
from typing import List, Dict

from sqlalchemy import or_, BigInteger, cast

from .models import session_scope, Gadget, Name, MirrorEdge, CompletedMirror
from .runner import local_toggles_runner


# class SingleDefinitionMapping(collections.abc.MutableMapping):
#   def __init__(self, *args, **kwargs):
#     self._dict = dict(*args, **kwargs)
#   def __getitem__(self, key):
#     return self._dict[key]
#   def __setitem__(self, key, value):
#     if key in self:
#       raise ValueError('{} {} {}'.format(key, self[key], value))
#     self._dict[key] = value
#   def __delitem__(self, key):
#     del self._dict[key]
#   def __iter__(self):
#     return iter(self._dict)
#   def __len__(self):
#     return len(self._dict)


def sync_known_gadgets(args):
    input_data = yaml.load(args.input)

    enantio_prefix = ('r', 's')
    canonicals = []
    names: Dict[str, int] = {}  # indices into canonicals (above)
    groups: Dict[str, List[str]] = {}
    mirror_pairs = []
    for name, gadget in input_data['gadgets'].items():
        for required_key in ('uedges', 'dedges'):
            if required_key not in gadget:
                gadget[required_key] = []
        morphs = local_toggles_runner(args, 'canonicalize', gadget)

        # We are chiral if any state has enantiomorphs.
        chiral = any((m[1] for m in morphs))
        if len(morphs) == 1 and not chiral:
            names[name] = len(canonicals)
            canonicals.append(morphs[0][0])
        if len(morphs) == 1 and chiral:
            morphs = morphs[0]
            names['r-'+name] = len(canonicals)
            canonicals.append(morphs[0])
            names['s-'+name] = len(canonicals)
            canonicals.append(morphs[1])
            groups[name] = [p+name for p in ('r-', 's-')]
            mirror_pairs.append(tuple((names[n] for n in groups[name])))
        if len(morphs) > 1 and not chiral:
            morphs = [m[0] for m in morphs]
            for index, q in enumerate(morphs):
                names['{}-{}'.format(name, index)] = len(canonicals)
                canonicals.append(q)
            groups[name] = ['{}-{}'.format(name, index) for index in range(len(morphs))]
        if len(morphs) > 1 and chiral:
            for si, qs in enumerate(morphs):
                mp = []
                names['r-{}-{}'.format(name, si)] = len(canonicals)
                mp.append(len(canonicals))
                canonicals.append(qs[0])
                if morphs[si][1]:
                    names['s-{}-{}'.format(name, si)] = len(canonicals)
                    mp.append(len(canonicals))
                    canonicals.append(qs[1])
                    mirror_pairs.append(tuple(mp))
                else:
                    names['s-{}-{}'.format(name, si)] = names['r-{}-{}'.format(name, si)]
                    # no mirror pair for achiral states
            groups[name] = ['{}-{}-{}'.format(enantio_prefix[pi], name, si) for pi in range(2) for si in range(len(morphs))]

    for name, target in input_data['aliases'].items():
        if name in names:
            # Might be an autogenerated chiral and/or state name, but those are obvious in output.
            print('ERROR: alias {} (intended for {}) already names a gadget'.format(name, target))
            sys.exit(1)
        if name in groups:
            print('ERROR: alias {} (intended for {}) already names an alias group (expanding to {})'.format(name, target, groups[name]))
            sys.exit(1)

        if target in names:
            groups[name] = [target]
        if target in groups:
            groups[name] = groups[target]

    with session_scope() as session:
        gadget_id_map = {}
        for index, gadget in enumerate(canonicals):
            g = session.query(Gadget.id).filter_by(data=gadget[-1]).one_or_none()
            if g:
                gadget_id_map[index] = g[0]
            if not g:
                g = Gadget.from_tuple(gadget)
                session.add(g)
                session.flush()  # we need the id
                gadget_id_map[index] = g.id

        for a, b in mirror_pairs:
            a, b = gadget_id_map[a], gadget_id_map[b]
            assert a != b, '{} {}'.format(a, b)  # indicates an error in the toggles runner
            a, b = min(a, b), max(a, b)
            # I'm assuming we have an exclude constraint ensuring the edge table is a mapping.
            e = session.query(MirrorEdge).filter(or_(MirrorEdge.a == a, MirrorEdge.b == b)).one_or_none()
            if not e:
                session.add(MirrorEdge(a=a, b=b))

        # We evaluated mirrors for everything, even achiral things, so mark
        # everything completed.
        for g in gadget_id_map.values():
            c = session.query(CompletedMirror).filter(CompletedMirror.r.contains(cast(g, BigInteger))).one_or_none()
            if not c:
                session.add(CompletedMirror.singleton(g))

        # It's much easier to just wipe this table and start over.
        session.query(Name).delete(synchronize_session='fetch')
        for name, local_id in names.items():
            session.add(Name(gadget_id=gadget_id_map[local_id], name=name))
        for name, targets in groups.items():
            targets = {gadget_id_map[names[t]] for t in targets}
            for target in targets:
                session.add(Name(gadget_id=target, name=name))




def register_subcommand(parser: argparse.ArgumentParser, subparser_holder: argparse._SubParsersAction):
    skg_parser = subparser_holder.add_parser('sync-known-gadgets')
    skg_parser.add_argument('input', type=argparse.FileType(), help='YAML file of gadget and alias definitions')
    skg_parser.set_defaults(command_func=sync_known_gadgets)
